---

- name: Install Update CRON
  template:
    src="puppetlabs-mirror.j2"
    dest="{{ mirror_cron_dir }}/puppetlabs-mirror"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0700

- name: Setup CRON Schedule
  cron:
    name="PuppetLabs"
    minute="{{ puppetlabs_mirror_cron_minute }}"
    hour="{{ puppetlabs_mirror_cron_hour }}"
    user="{{ mirror_unix_user }}"
    state="present"
    job="{{ mirror_cron_dir }}/puppetlabs-mirror >/dev/null 2>&1"
    disabled="{{ puppetlabs_mirror_cron_disabled }}"

- stat:
    path="{{ mirror_timestamp_dir }}/puppetlabs"
  register: tsfile

- name: Seed Timestamp File
  copy:
    content="0"
    dest="{{ mirror_timestamp_dir }}/puppetlabs"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0644
  when: not tsfile.stat.exists
