---

- name: Install Update CRON
  template:
    src="puppetlabs-mirror.j2"
    dest="{{ mirror_cron_dir }}/puppetlabs-mirror"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0700

- name: Setup CRON Schedule
  cron:
    name="PuppetLabs"
    minute="{{ puppetlabs_mirror_cron_minute }}"
    hour="{{ puppetlabs_mirror_cron_hour }}"
    user="{{ mirror_unix_user }}"
    state="present"
    job="{{ mirror_cron_dir }}/puppetlabs-mirror"
    disabled="{{ puppetlabs_mirror_cron_disabled }}"
